CREATE DATABASE IF NOT EXISTS dhnaturally_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dhnaturally_db;

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  name_he TEXT NOT NULL,
  description TEXT NOT NULL,
  description_he TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  imageName VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name(191)),
  INDEX idx_price (price),
  INDEX idx_created_at (created_at)
);

-- Ensure bilingual columns exist for older schemas that predate these fields.
SET @cnt := (SELECT COUNT(*) FROM information_schema.COLUMNS
              WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'name_he');
SET @sql := IF(@cnt = 0, 'ALTER TABLE products ADD COLUMN name_he TEXT AFTER name', 'SELECT "name_he exists"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @cnt := (SELECT COUNT(*) FROM information_schema.COLUMNS
              WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'description_he');
SET @sql := IF(@cnt = 0, 'ALTER TABLE products ADD COLUMN description_he TEXT AFTER description', 'SELECT "description_he exists"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure `name` column can be safely changed to TEXT by dropping/recreating index if needed.
SET @idx_cnt := (SELECT COUNT(*) FROM information_schema.STATISTICS
                  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND INDEX_NAME = 'idx_name');
SET @sql := IF(@idx_cnt = 1, 'ALTER TABLE products DROP INDEX idx_name', 'SELECT "idx_name missing"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @cnt := (SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'name');
SET @sql := IF(@cnt = 1, 'ALTER TABLE products MODIFY COLUMN name TEXT NOT NULL', 'SELECT "name column missing"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @cnt := (SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'name');
SET @sql := IF(@cnt = 1, 'CREATE INDEX idx_name ON products (name(191))', 'SELECT "name column missing"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT INTO products (id, name, name_he, description, description_he, price, imageName) VALUES
(UUID(), 'Anacardium Orientale', 'אנקארדיום אוריינטליס', 'Marking nut tree Mind and nervous system, mental confusion, anxiety, split personality, Mental confusion, anxiety, and feelings of split personality, Conflict between good and evil impulses, Lack of confidence and mental weakness, Profound anxiety about the future, Maliciousness and cruelty tendencies, Brain fog and difficulty concentrating, Digestive symptoms relieved by eating, Constipation with constant urge but difficult passage, Skin conditions with intense itching and vesicular eruptions, Pains described as dull plugs being pushed into the body Modalities: Worse from emotional distress, mental exertion, hot weather, empty stomach; Better from eating, resting, warmth', ' עץ אגוז סימון  מוח ומערכת עצבים, בלבול מנטלי, חרדה, אישיות מפוצלת, בלבול מנטלי, חרדה ותחושות של אישיות מפוצלת, קונפליקט בין דחפים טובים לרעים, חוסר ביטחון וחולשה מנטלית, חרדה עמוקה לגבי העתיד, נטיות לזדון ואכזריות, ערפל מוחי וקושי בריכוז, תסמינים עיכוליים שמשתפרים מאכילה, עצירות עם דחף קבוע אך קושי במעבר, מצבי עור עם גירוד עז ופריחות שלפוחיות, כאבים המתוארים כפקקים עמומים הנדחפים לתוך הגוף מחמיר מלחץ רגשי, מאמץ מנטלי, מזג אוויר חם, קיבה ריקה; משתפר מאכילה, מנוחה, חום', 169.90, 'product.png'),
(UUID(), 'Antimonium Crudum', 'אנטימוניום קרודום', 'Antimony trisulphide mineral Digestive system, skin, mind, Irritability and sulkiness, especially in children, Thick, white-coated tongue, Indigestion from overeating rich/fatty foods, Alternating diarrhea and constipation, Thickened skin, horny warts, calluses, Corns on feet that are very tender, Headaches with heaviness and vertigo, Respiratory cough with mucus and burning chest Modalities: Worse from heat, sun heat, cold bathing, rich/acidic foods; Better from open air, rest, moist warmth', ' מינרל אנטימון טריסולפיד  מערכת עיכול, עור, מוח, עצבנות ורוגז, במיוחד אצל ילדים, לשון עבה עם ציפוי לבן, עיכול לקוי מאכילת יתר של מזונות עשירים/שומניים, שלשול ועצירות מתחלפים, עור מועך, יבלות קרניות, קלוסים, יבלות בכפות הרגליים הרגישות מאוד, כאבי ראש עם כבדות וסחרחורת, שיעול נשימתי עם ליחה ושריפה בחזה מחמיר מחום, חום שמש, רחצה קרה, מזונות עשירים/חומציים; משתפר מאוויר פתוח, מנוחה, חום לח', 169.90, 'product.png'),
(UUID(), 'Apis Mellifica', 'אפיס מליפיקה', 'Honeybee venom Inflammatory conditions mimicking bee stings, Sudden swelling and edema (pale pink/rosy color), Stinging, burning, pricking pains, Puffiness of face and eyelids, Lack of thirst despite dry mouth/fever, Throat swelling with fiery red color and uvula like "sac of water", Urinary tract infections with stinging/burning and scanty urine, Hives and allergic rashes with stinging sensation, Restlessness, irritability, apathy in severe cases Modalities: Worse from heat, touch, pressure, right side; Better from cold applications, cold air', ' ארס דבורת דבש  מצבים דלקתיים המחקים עקיצות דבורים, נפיחות ונפיחות פתאומית (צבע ורוד חיוור/ורוד), כאבים עוקצים, שורפים, דוקרים, נפיחות בפנים ועפעפיים, חוסר צמא למרות פה יבש/חום, נפיחות בגרון עם צבע אדום לוהט וענבל כמו "שק מים", זיהומים בדרכי השתן עם עקיצה/שריפה ושתיון מועט, כוורות ופריחות אלרגיות עם תחושת עקיצה, חוסר מנוחה, עצבנות, אדישות במקרים חמורים מחמיר מחום, מגע, לחץ, צד ימין; משתפר מיישומים קרים, אוויר קר', 169.90, 'product.png'),
(UUID(), 'Arnica Montana', 'ארניקה מונטנה', 'Sunflower family plant Physical trauma, injury, overexertion, Bruises, swelling, and bruised soreness, Post-surgical healing and pain reduction, Muscular overexertion and soreness, Black eyes and blunt trauma, Deep bruised sensation, bed feels too hard, Fear of being touched due to pain, Mental effects of trauma and shock, Offensive odors from bodily discharges Modalities: Worse from touch, motion, cold, damp weather; Better from lying down with head low, rest', ' צמח ממשפחת החמניות  טראומה פיזית, פציעה, מאמץ יתר, חבורות, נפיחות וכאב חבורות, ריפוי לאחר ניתוח והפחתת כאב, מאמץ יתר שרירי וכאב, עיניים שחורות וטראומה קהה, תחושת חבורה עמוקה, המיטה מרגישה קשה מדי, פחד מגע בגלל כאב, השפעות מנטליות של טראומה וזעזוע, ריחות רעים מהפרשות גופניות מחמיר מגע, תנועה, קור, מזג אוויר לח; משתפר משכיבה עם ראש נמוך, מנוחה', 169.90, 'product.png'),
(UUID(), 'Arsenicum Album', 'ארסניקום אלבום', 'Arsenic trioxide mineral Anxiety, burning pains, profound weakness, Intense anxiety and fear (death, disease, being alone), Mental and physical restlessness with exhaustion, Burning pains throughout body (like hot coals), Profound weakness and prostration, Periodic symptoms (3 AM aggravation), Gastrointestinal burning and watery, acrid diarrhea, Respiratory tightness with dry cough, Skin dryness and scaly eruptions Modalities: Worse from cold, cold drinks, 12-2 AM, right side, exertion; Better from warmth, warm drinks, company, elevated position', ' מינרל ארסן טריאוקסיד  חרדה, כאבי שריפה, חולשה עמוקה, חרדה עזה ופחד (מוות, מחלה, היות לבד), חוסר מנוחה מנטלי ופיזי עם תשישות, כאבי שריפה בכל הגוף (כמו גחלים לוהטות), חולשה עמוקה והתמוטטות, תסמינים תקופתיים (החמרה בשעה 3 לפנות בוקר), שריפה במערכת העיכול ושלשול מימי חריף, צפיפות נשימתית עם שיעול יבש, יובש עור ופריחות קשקשיות מחמיר מקור, משקאות קרים, 12-2 לפנות בוקר, צד ימין, מאמץ; משתפר מחום, משקאות חמים, חברה, עמדה מוגבהת', 169.90, 'product.png'),
(UUID(), 'Baryta Carbonica', 'בריטה קרבוניקה', 'Barium carbonate Developmental arrest, glandular swelling, Shyness, timidity, fear of strangers, Lack of confidence and fear of judgment, Intellectual immaturity and poor memory, Physical underdevelopment and stunted growth, Swollen cervical tonsils and glands, Recurrent tonsillitis with pus formation, Cardiovascular hardening of arteries, Digestive swelling and abdominal discomfort Modalities: Worse from cold, damp weather, drafts, mental exertion; Better from warmth, familiar environment', ' בריום קרבונט  עצירת התפתחות, נפיחות בלוטות, ביישנות, פחדנות, פחד מזרים, חוסר ביטחון ופחד משיפוט, בגרות אינטלקטואלית וזיכרון לקוי, התפתחות פיזית לקויה וגדילה מוגבלת, טונסילים ובלוטות צוואר נפוחות, דלקת גרון חוזרת עם יצירת מוגלה, התקשות עורקים קרדיווסקולרי, נפיחות עיכולית ואי נוחות בבטן מחמיר מקור, מזג אוויר לח, טיוטות, מאמץ מנטלי; משתפר מחום, סביבה מוכרת', 169.90, 'product.png'),
(UUID(), 'Baryta Muriatica', 'בריטה מוריאטיקה', 'Barium chloride Nervous system degeneration, inflammatory conditions, Nervous system degeneration and paralysis, Aneurysms and hardened arteries, Inflammatory glandular swelling, Restlessness and aggression, Multiple sclerosis symptoms, Stroke sequelae, Hard, painful glands and tonsils Modalities: Worse from cold, damp weather, drafts; Better from warmth', ' בריום כלוריד  ניוון מערכת עצבים, מצבים דלקתיים, ניוון מערכת עצבים ושיתוק, אנוריזמות ועורקים מוקשחים, נפיחות בלוטות דלקתית, חוסר מנוחה ואגרסיביות, תסמיני טרשת נפוצה, השלכות שבץ, בלוטות וטונסילים קשים וכואבים מחמיר מקור, מזג אוויר לח, טיוטות; משתפר מחום', 169.90, 'product.png'),
(UUID(), 'Bryonia Alba', 'בריוניה אלבה', 'Wild hop plant Serous membranes (lungs, pleura, peritoneum), Aggravation from slightest motion, Extreme dryness of mucous membranes, Irritability and aversion to disturbance, Sharp, stitching pains worse from motion, Dry, hard cough with chest pain, Joint pains hot, swollen, worse from motion, Headaches worse from coughing/stooping, Bitter taste and constipation with hard stools Modalities: Worse from motion, warmth, change of weather, night; Better from absolute rest, lying on painful side, pressure', ' צמח הופ בר  קרומות סרוזיות (ריאות, פלוארה, פריטונאום), החמרה מהתנועה הקלה ביותר, יובש קיצוני של ריריות, עצבנות ורתיעה מהפרעה, כאבים חדים, תופרים מחמירים מתנועה, שיעול יבש קשה עם כאב בחזה, כאבי מפרקים חמים, נפוחים, מחמירים מתנועה, כאבי ראש מחמירים משיעול/כיפוף, טעם מר ועצירות עם צואה קשה מחמיר מתנועה, חום, שינוי מזג אוויר, לילה; משתפר ממנוחה מוחלטת, שכיבה על הצד הכואב, לחץ', 169.90, 'product.png'),
(UUID(), 'Caffea Cruda', 'קפאה קרודה', 'Unroasted coffee beans Nervous system overstimulation, Insomnia from overactive mind, Physical and mental restlessness, Hypersensitivity to pain, noise, light, touch, Elation and excitement alternating with agitation, Sharp, shooting pains throughout body, Headaches after excitement or lack of sleep, Toothaches from nervousness, Menstrual cramps with extreme restlessness Modalities: Worse from excitement, joy, noise, odors, cold, open air; Better from warmth, warm bath, lying down', ' פולי קפה לא קלויים  עודף גירוי במערכת העצבים, נדודי שינה ממוח פעיל מדי, חוסר מנוחה פיזי ומנטלי, רגישות יתר לכאב, רעש, אור, מגע, התרוממות רוח והתרגשות מתחלפות עם התרגשות, כאבים חדים, יורים בכל הגוף, כאבי ראש לאחר התרגשות או חוסר שינה, כאבי שיניים מהעצבנות, התכווצויות וסת עם חוסר מנוחה קיצוני מחמיר מהתרגשות, שמחה, רעש, ריחות, קור, אוויר פתוח; משתפר מחום, אמבט חם, שכיבה', 169.90, 'product.png'),
(UUID(), 'Calcarea Carbonica', 'קלקריאה קרבוניקה', 'Oyster shells (calcium carbonate) Constitutional remedy for metabolic issues, Tendency to gain weight easily, slow metabolism, Poor stamina and weakness, sensitivity to cold, Head sweating during sleep, Responsible but anxious temperament, Cravings for eggs, sweets, dairy, Constipation or sluggish digestion, Bone and teeth problems, Hormonal and menstrual irregularities Modalities: Worse from cold, damp, exertion, mental stress, milk; Better from dry weather, lying on painful side', ' קונכיות צדפות (קלציום קרבונט)  תרופה חוקתית לבעיות מטבוליות, נטייה להשמנה בקלות, מטבוליזם איטי, סיבולת לקויה וחולשה, רגישות לקור, הזעת ראש במהלך שינה, מזג אחראי אך חרד, תשוקות לביצים, מתוקים, מוצרי חלב, עצירות או עיכול איטי, בעיות בעצמות ושיניים, חוסר סדירות הורמונלי ווסתי מחמיר מקור, לחות, מאמץ, לחץ מנטלי, חלב; משתפר ממזג אוויר יבש, שכיבה על הצד הכואב', 169.90, 'product.png'),
(UUID(), 'Calendula Officinalis', 'קלנדולה אופיצינליס', 'Common marigold plant Wounds, injuries, infections, Promotes healthy tissue granulation, Primary remedy for open wounds and cuts, Prevents and treats wound infections, Hot, red, swollen areas with pus formation, Traumatic injuries and lacerations, Post-surgical healing without scarring, First-aid remedy for any injury, Anti-inflammatory and antiseptic properties Modalities: Worse from touch, motion, damp weather; Better from rest, warmth', ' צמח קלנדולה רגילה  פצעים, פציעות, זיהומים, מקדם גרנולציה בריאה של רקמות, תרופה עיקרית לפצעים פתוחים וחתכים, מונע ומטפל בזיהומי פצעים, אזורים חמים, אדומים, נפוחים עם יצירת מוגלה, פציעות טראומטיות וקרעים, ריפוי לאחר ניתוח ללא צלקות, תרופת עזרה ראשונה לכל פציעה, תכונות אנטי דלקתיות ונוגדות חיידקים מחמיר מגע, תנועה, מזג אוויר לח; משתפר ממנוחה, חום', 169.90, 'product.png'),
(UUID(), 'Carbo Vegetabilis', 'קרבו וגטביליס', 'Vegetable charcoal Digestive and circulatory systems, Extreme prostration and collapse, Cold, clammy sweat and icy extremities, Air hunger and gasping for breath, Massive abdominal bloating and gas, Belching providing temporary relief, Poor circulation and venous stasis, Weak voice and bed sores, Heartburn and sour eructations Modalities: Worse from evening, cold, warmth, exertion, rich food; Better from fanning, fresh air, belching', ' פחם צמחי  מערכות עיכול ומחזור דם, התמוטטות והתמוטטות קיצונית, זיעה קרה, דביקה וגפיים קפואות, רעב אוויר והתנשפות לנשימה, נפיחות בטנית עצומה וגזים, גיהוק המספק הקלה זמנית, מחזור דם לקוי וסטזיס ורידי, קול חלש ופצעי מיטה, צריבה וגיהוקים חמוצים מחמיר מערב, קור, חום, מאמץ, מזון עשיר; משתפר ממניפה, אוויר צח, גיהוק', 169.90, 'product.png'),
(UUID(), 'Caulophyllum Thalictroides', 'קאולופילום תליקטרואידס', 'Blue cohosh plant Female reproductive system, Ineffectual labor pains (weak, short, erratic), False labor pains, Spasmodic menstrual cramps, Irregular or scanty menstruation, Uterine weakness and recurrent miscarriages, Joint pains associated with hormonal changes, Small joint rheumatism Modalities: Worse from drafts, cold weather, mental/physical exertion; Better from warmth, warm room', ' צמח קוהוש כחול  מערכת רבייה נשית, כאבי לידה לא יעילים (חלשים, קצרים, לא סדירים), כאבי לידה כוזבים, התכווצויות וסתיות ספסטיות, וסת לא סדירה או מועטה, חולשה רחמית והפלות חוזרות, כאבי מפרקים הקשורים לשינויים הורמונליים, רומטיזם במפרקים קטנים מחמיר מטיוטות, מזג אוויר קר, מאמץ מנטלי/פיזי; משתפר מחום, חדר חם', 169.90, 'product.png'),
(UUID(), 'Colchicum Autumnale', 'קולצ׳יקום אוטומנלה', 'Autumn crocus plant Musculoskeletal system, gout, Intense gout pain (red, hot, swollen joints), Extreme sensitivity to smells (cooking odors), Nausea and faintness from food smells, Tearing, stitching pains in small joints, Profound disgust for food, Greenish-brown watery diarrhea, Scanty, dark urine with sediment, Headaches and irritability Modalities: Worse from motion, cold, touch, night, evening; Better from warmth, rest', ' צמח קרוקוס סתיו  מערכת שריר ושלד, שיגדון, כאב שיגדון עז (מפרקים אדומים, חמים, נפוחים), רגישות קיצונית לריחות (ריחות בישול), בחילה והתעלפות מריחות מזון, כאבים קורעים, תופרים במפרקים קטנים, גועל עמוק ממזון, שלשול מימי חום-ירוק, שתן מועט, כהה עם משקע, כאבי ראש ועצבנות מחמיר מתנועה, קור, מגע, לילה, ערב; משתפר מחום, מנוחה', 169.90, 'product.png'),
(UUID(), 'Fel Tauri', 'פל טאורי', 'Ox bile Liver and gallbladder health, Liver congestion and enlargement, Gallstones and biliary colic, Jaundice from bile duct obstruction, High cholesterol and fat emulsification, Indigestion after rich/fatty foods, Flatulence and gurgling abdomen, Sleepiness after eating, Portal vein congestion symptoms Modalities: Worse from lying on right side, cold; Better from warmth, hot water bottle on liver', ' מרה שור  בריאות כבד וכיס מרה, עומס בכבד והגדלה, אבני מרה וקוליקה ביליארית, צהבת מחסימת צינור מרה, כולסטרול גבוה ואמולסיפיקציה של שומנים, עיכול לקוי לאחר מזונות עשירים/שומניים, נפיחות ובטן מגרגרת, ישנוניות לאחר אכילה, תסמיני עומס וריד שער מחמיר משכיבה על צד ימין, קור; משתפר מחום, בקבוק מים חמים על הכבד', 169.90, 'product.png'),
(UUID(), 'Ginkgo Biloba', 'גינקו בילובה', 'Ancient Ginkgo tree leaves Cerebral and peripheral circulation, Memory and concentration decline, Mental fogginess and absent-mindedness, Dizziness and vertigo from poor circulation, Throbbing headaches, Cold extremities and numbness, Tinnitus (buzzing/ringing ears), Antioxidant and anti-inflammatory effects, General weakness and fatigue Modalities: Worse from mental exertion; Better from fresh air, rest', ' עלי עץ גינקו עתיק  מחזור דם מוחי והיקפי, ירידה בזיכרון וריכוז, ערפל מנטלי ושכחנות, סחרחורת וורטיגו ממחזור דם לקוי, כאבי ראש פועמים, גפיים קרות והרדמות, טיניטוס (זמזום/צלצול באוזניים), השפעות נוגדות חמצון ואנטי דלקתיות, חולשה כללית ועייפות מחמיר ממאמץ מנטלי; משתפר מאוויר צח, מנוחה', 169.90, 'product.png'),
(UUID(), 'Graphites', 'גרפיטס', 'Black lead (graphite) Skin, digestive system, hormonal balance, Lack of confidence and timidity, Tearfulness and brooding sadness, Thick, honey-colored, sticky skin eruptions, Chronic eczema and dermatitis, Constipation with large, knotty stools, Obesity and slow metabolism, Menstrual irregularities, Brittle nails and hair Modalities: Worse from warmth of bed, cold weather, scratching; Better from open air, walking', ' עופרת שחורה (גרפיט)  עור, מערכת עיכול, איזון הורמונלי, חוסר ביטחון ופחדנות, דמענות ועצב מהורהר, פריחות עור עבות, צבע דבש, דביקות, אקזמה כרונית ודרמטיטיס, עצירות עם צואה גדולה, קשרית, השמנה ומטבוליזם איטי, חוסר סדירות וסתית, ציפורניים ושיער שביר מחמיר מחום המיטה, מזג אוויר קר, גירוד; משתפר מאוויר פתוח, הליכה', 169.90, 'product.png'),
(UUID(), 'Green Tea (Camellia Sinensis)', 'תה ירוק (קמליה סיננסיס)', 'Tea plant Nervous system and sleep, Nervous sleeplessness and insomnia, Racing thoughts and mental agitation, Heart palpitations from anxiety, Dyspepsia and sluggish digestion, Antioxidant and anti-inflammatory effects, Appetite regulation and weight management, Blood pressure and cholesterol support Modalities: Worse from evening, mental exertion; Better from fresh air, light exercise', ' צמח תה  מערכת עצבים ושינה, נדודי שינה עצביים, מחשבות מהירות והתרגשות מנטלית, דפיקות לב מחרדה, דיספפסיה ועיכול איטי, השפעות נוגדות חמצון ואנטי דלקתיות, ויסות תיאבון וניהול משקל, תמיכה בלחץ דם וכולסטרול מחמיר מערב, מאמץ מנטלי; משתפר מאוויר צח, פעילות גופנית קלה', 169.90, 'product.png'),
(UUID(), 'Hypericum Perforatum', 'היפריקום פרפורטום', 'St. John''s Wort plant Nerve injuries and pain, Injuries to nerve-rich areas (spine, fingers, toes), Sharp, shooting, lightning-like pains, Crushed fingers/toes and puncture wounds, Spinal injuries and whiplash, Post-surgical nerve pain, Depression from physical injury, Convulsions from head trauma, Pains radiating along nerve pathways Modalities: Worse from touch, cold, fog, motion; Better from rest, warmth, lying down', ' צמח סנט ג׳ון וורט  פציעות עצבים וכאב, פציעות באזורים עשירי עצבים (עמוד שדרה, אצבעות, בהונות), כאבים חדים, יורים, כמו ברק, אצבעות/בהונות מרוסקות ופצעי דקירה, פציעות עמוד שדרה וצליפת שוט, כאב עצבים לאחר ניתוח, דיכאון מפציעה פיזית, התכווצויות מפגיעת ראש, כאבים המוקרנים לאורך נתיבי עצבים מחמיר מגע, קור, ערפל, תנועה; משתפר ממנוחה, חום, שכיבה', 169.90, 'product.png'),
(UUID(), 'Ignatia Amara', 'איגנטיה אמרה', 'St. Ignatius bean Emotional trauma and grief, Acute grief, disappointment, shock, Hysterical outbursts and mood swings, Paradoxical symptoms (pain better from pressure), Globus hystericus (lump in throat), Spasmodic twitching and muscle spasms, Headaches like nail driven into head, Sore throat with paradoxical swallowing relief, Heart palpitations and sighing Modalities: Worse from emotional distress, grief, strong odors, consolation; Better from changing position, diversion, eating', ' פול סנט איגנטיוס  טראומה רגשית ואבל, אבל חריף, אכזבה, זעזוע, התפרצויות היסטריות ושינויי מצב רוח, תסמינים פרדוקסליים (כאב משתפר מלחץ), גלובוס היסטריקוס (גוש בגרון), התכווצויות ספסטיות ורעידות שרירים, כאבי ראש כמו מסמר הננעץ בראש, גרון כואב עם הקלה פרדוקסלית מבליעה, דפיקות לב ואנחות מחמיר מלחץ רגשי, אבל, ריחות חזקים, ניחומים; משתפר משינוי עמדה, הסחה, אכילה', 169.90, 'product.png'),
(UUID(), 'Iris Versicolor', 'איריס ורסיקולור', 'Blue Flag plant Digestive system, migraines, Sick headaches with nausea and vomiting, Blurred vision and visual aura, Burning along alimentary canal, Vomiting sour, watery, or bilious material, Diarrhea with burning anus, Pancreatic and salivary gland issues, Profuse saliva flow, Eczema and skin eruptions Modalities: Worse from evening, mental exertion, cold weather; Better from gentle motion, warmth', ' צמח דגל כחול  מערכת עיכול, מיגרנות, כאבי ראש חולים עם בחילה והקאות, ראייה מטושטשת ואאורה ויזואלית, שריפה לאורך תעלת העיכול, הקאות חמוצות, מימיות או מרירות, שלשול עם שריפה בפי הטבעת, בעיות בלוטת הלבלב ובלוטות הרוק, זרימה מרובה של רוק, אקזמה ופריחות עור מחמיר מערב, מאמץ מנטלי, מזג אוויר קר; משתפר מתנועה עדינה, חום', 169.90, 'product.png'),
(UUID(), 'Ledum Palustre', 'לדום פלוסטר', 'Wild rosemary plant Puncture wounds, joints, insect bites, Puncture wounds from sharp objects, Insect bites and stings (bees, wasps, ticks), Black eyes and bruises, Gout starting in lower limbs ascending upward, Rheumatism with shifting pains, Sprains in ankles with false step sensation, Paradoxical cold relief for hot, swollen joints Modalities: Worse from warmth, heat of bed, covering affected area; Better from cold applications, cold air, cool surroundings', ' צמח רוזמרין בר  פצעי דקירה, מפרקים, עקיצות חרקים, פצעי דקירה מחפצים חדים, עקיצות ונשיכות חרקים (דבורים, צרעות, קרציות), עיניים שחורות וחבורות, שיגדון המתחיל בגפיים תחתונות עולה למעלה, רומטיזם עם כאבים נודדים, נקעים בקרסוליים עם תחושת צעד כוזב, הקלה פרדוקסלית מקור למפרקים חמים, נפוחים מחמיר מחום, חום המיטה, כיסוי האזור הפגוע; משתפר מיישומים קרים, אוויר קר, סביבה קרירה', 169.90, 'product.png'),
(UUID(), 'Lycopodium Clavatum', 'ליקופודיום קלאווטום', 'Club moss spores Liver, digestive system, urinary tract, Lack of self-confidence and fear of failure, Compensatory arrogance and boasting, Digestive bloating and gas (loud rumbling), Liver congestion and right-sided symptoms, Constipation with difficult, incomplete evacuation, Urinary pain and red sandy sediment, Headaches and respiratory congestion, Cravings for sweets and warm foods Modalities: Worse from 4-8 PM, heat, wrapping up warm, rich foods; Better from warm drinks, open air, passing gas', ' נבגי אברש בר  כבד, מערכת עיכול, דרכי שתן, חוסר ביטחון עצמי ופחד מכישלון, יהירות פיצוי וגאווה, נפיחות עיכול וגזים (גרגור חזק), עומס בכבד ותסמינים בצד ימין, עצירות עם פינוי קשה, לא שלם, כאב בשתן ומשקע חולי אדום, כאבי ראש ועומס נשימתי, תשוקות למתוקים ומזונות חמים מחמיר מ-16:00-20:00, חום, עטיפה חמה, מזונות עשירים; משתפר ממשקאות חמים, אוויר פתוח, מעבר גזים', 169.90, 'product.png'),
(UUID(), 'Natrum Muriaticum', 'נתרום מוריאטיקום', 'Sodium chloride (table salt) Emotional sensitivity, fluid balance, Grief, suppressed emotions, introversion, Aversion to consolation when sad, Headaches worse in sun, better pressure, Dry mucous membranes alternating with watery discharges, Cold sores around lips, Constipation with crumbling stools, Colds with egg-white nasal discharge, Cravings for salty foods Modalities: Worse from sun, heat, 10-11 AM, consolation; Better from cool open air, lying on right side', ' נתרן כלוריד (מלח שולחן)  רגישות רגשית, איזון נוזלים, אבל, רגשות מדוכאים, אינטרוברסיה, התנגדות לניחומים כשעצוב, כאבי ראש מחמירים בשמש, משתפרים מלחץ, ריריות יבשות המתחלפות עם הפרשות מימיות, כיבים קרים סביב השפתיים, עצירות עם צואה מתפוררת, הצטננויות עם הפרשת אף כמו חלבון ביצה, תשוקות למזונות מלוחים מחמיר משמש, חום, 10-11 בבוקר, ניחומים; משתפר מאוויר פתוח קריר, שכיבה על צד ימין', 169.90, 'product.png'),
(UUID(), 'Natrum Sulphuricum', 'נתרום סולפוריקום', 'Sodium sulfate (Glaubers salt) Liver, digestive system, respiratory system, Sensitive liver and bilious colic, Greenish-brown watery stools, Bitter taste and vomiting bile, Asthma and bronchitis worse in damp weather, Head injuries and concussion effects, Memory loss and mental confusion, Gout and rheumatism worse in dampness, Jaundice and bile duct obstruction Modalities: Worse from damp weather, lying on left side, cold; Better from dry weather, pressure, warmth', ' נתרן סולפט (מלח גלאובר)  כבד, מערכת עיכול, מערכת נשימה, כבד רגיש וקוליקה ביליארית, צואה מימית ירוק-חום, טעם מר והקאות מרה, אסתמה וברונכיטיס מחמירים במזג אוויר לח, פגיעות ראש ואפקטים של חבלה, אובדן זיכרון ובלבול מנטלי, שיגדון ורומטיזם מחמירים בלחות, צהבת וחסימת צינור מרה מחמיר ממזג אוויר לח, שכיבה על צד שמאל, קור; משתפר ממזג אוויר יבש, לחץ, חום', 169.90, 'product.png'),
(UUID(), 'Nux Vomica', 'נוקס וומיקה', 'Poison nut tree seeds Liver and digestive system, Liver congestion and digestive complaints, Irritability and impatience, Overindulgence effects (food, alcohol, work), Constipation with ineffectual urging, Heartburn and acid reflux, Headaches from digestive issues, Insomnia from mental overactivity, Chilliness and sensitivity to cold Modalities: Worse from morning, cold, touch, noise, light; Better from evening, warmth, rest', ' זרעי עץ אגוז רעל  כבד ומערכת עיכול, עומס בכבד ותלונות עיכול, עצבנות וחוסר סבלנות, השפעות של התפרעות יתר (מזון, אלכוהול, עבודה), עצירות עם דחף לא יעיל, צריבה וריפלוקס חומצי, כאבי ראש מבעיות עיכול, נדודי שינה מפעילות מנטלית יתר, צינון ורגישות לקור מחמיר מבוקר, קור, מגע, רעש, אור; משתפר מערב, חום, מנוחה', 169.90, 'product.png'),
(UUID(), 'Phytolacca Decandra', 'פיטולקה דקנדרה', 'Pokeweed plant Glandular system, throat, musculoskeletal, Glandular swelling and inflammation, Mastitis with hard, hot, painful breasts, Sore throats with dark red/purple tonsils, Electric shock-like joint pains, Muscular stiffness and soreness, Indifference and apathy from pain, Ulcers and skin lesions, Teething with irresistible biting Modalities: Worse from cold, damp, night, motion, swallowing; Better from warmth, rest, rubbing affected parts', ' צמח פוקוויד  מערכת בלוטות, גרון, שריר ושלד, נפיחות בלוטות ודלקת, מסטיטיס עם שדיים קשים, חמים, כואבים, גרונות כואבים עם טונסילים אדומים כהים/סגולים, כאבי מפרקים כמו זרם חשמלי, נוקשות שרירית וכאב, אדישות ואפטיה מכאב, כיבים ופגיעות עור, הברקת שיניים עם נשיכה בלתי נשלטת מחמיר מקור, לחות, לילה, תנועה, בליעה; משתפר מחום, מנוחה, שפשוף האזורים הפגועים', 169.90, 'product.png'),
(UUID(), 'Psorinum', 'פסורינום', 'Scabies nosode Chronic conditions, skin, offensive discharges, Despair of recovery and hopelessness, Extreme anxiety and impending doom, Offensive odors from all bodily secretions, Intense itching worse from warmth, Chronic eczema and psoriasis, Respiratory asthma with suffocation, Weakness, anemia, and lack of vitality, Ravenous appetite especially at night Modalities: Worse from cold, drafts, warmth of bed, before storms; Better from warmth, being bundled up', ' נוזוד קרפדת  מצבים כרוניים, עור, הפרשות רעילות, ייאוש מהחלמה וחוסר תקווה, חרדה קיצונית ואסון מתקרב, ריחות רעים מכל הפרשות גופניות, גירוד עז מחמיר מחום, אקזמה כרונית ופסוריאזיס, אסתמה נשימתית עם חנק, חולשה, אנמיה וחוסר חיוניות, תיאבון עז במיוחד בלילה מחמיר מקור, טיוטות, חום המיטה, לפני סערות; משתפר מחום, עטיפה', 169.90, 'product.png'),
(UUID(), 'Berberis Vulgaris (Barberry)', 'ברבריס וולגריס (ברברי)', 'Barberry plant Diabetes management, Contains protoberberine alkaloids (berberine), Antihyperglycemic effects, Modest reductions in fasting plasma glucose, HbA1c improvements, HOMA-IR reductions, Small effects on post-prandial glucose, Gastrointestinal adverse effects possible, Contraindicated in pregnancy/lactation Clinical Evidence: RCTs show significant but modest glycemic control benefits', ' צמח ברברי  ניהול סוכרת, מכיל אלקלואידים פרוטוברביניים (ברברין), השפעות אנטי היפרגליקמיות, הפחתות צנועות בגלוקוז פלזמה בצום, שיפורים ב-HbA1c, הפחתות ב-HOMA-IR, השפעות קטנות על גלוקוז לאחר ארוחה, תופעות לוואי במערכת העיכול אפשריות, התווית נגד בהריון/הנקה ראיות קליניות: RCTs מראים יתרונות משמעותיים אך צנועים בשליטה גליקמית', 169.90, 'product.png'),
(UUID(), 'Gymnema Sylvestre', 'גימנמה סילווסטר', 'Gymnema plant Blood sugar regulation and diabetes, Reduces sugar cravings by blocking taste receptors, Lowers blood sugar levels and post-meal spikes, Supports insulin production and beta-cell regeneration, Improves cholesterol and triglyceride levels, Aids weight management and appetite suppression, Anti-inflammatory and immunomodulatory effects, Traditional Ayurvedic diabetes treatment Clinical Evidence: Meta-analyses show significant reductions in FPG, HbA1c, and lipids', ' צמח גימנמה  ויסות סוכר בדם וסוכרת, מפחית תשוקות לסוכר על ידי חסימת קולטני טעם, מוריד רמות סוכר בדם וזינוקים לאחר ארוחה, תומך בייצור אינסולין ורגנרציה של תאי בטא, משפר רמות כולסטרול וטריגליצרידים, מסייע בניהול משקל ודיכוי תיאבון, השפעות אנטי דלקתיות ואימונומודולטוריות, טיפול סוכרת איורוודי מסורתי ראיות קליניות: מטה-אנליזות מראות הפחתות משמעותיות ב-FPG, HbA1c, ושומנים', 169.90, 'product.png'),
(UUID(), 'Momordica Charantia (Bitter Melon)', 'מומורדיקה צ׳רנטיה (מלון מר)', 'Bitter melon plant Diabetes management, Blood sugar regulation, Insulin sensitivity improvement, Pancreatic function support, Anti-diabetic properties, Traditional diabetes treatment, Metabolic health support Clinical Evidence: Limited direct evidence for homeopathic use, but herbal form shows glycemic benefits', ' צמח מלון מר  ניהול סוכרת, ויסות סוכר בדם, שיפור רגישות לאינסולין, תמיכה בתפקוד הלבלב, תכונות אנטי סוכרתיות, טיפול סוכרת מסורתי, תמיכה בבריאות מטבולית ראיות קליניות: ראיות ישירות מוגבלות לשימוש הומאופתי, אך הצורה הצמחית מראה יתרונות גליקמיים', 169.90, 'product.png'),
(UUID(), 'Natrum Muriaticum', 'נתרום מוריאטיקום', 'Sodium chloride (table salt) Emotional sensitivity, fluid balance, Grief, suppressed emotions, introversion, Aversion to consolation when sad, Headaches worse in sun, better pressure, Dry mucous membranes alternating with watery discharges, Cold sores around lips, Constipation with crumbling stools, Colds with egg-white nasal discharge, Cravings for salty foods Modalities: Worse from sun, heat, 10-11 AM, consolation; Better from cool open air, lying on right side', ' נתרן כלוריד (מלח שולחן)  רגישות רגשית, איזון נוזלים, אבל, רגשות מדוכאים, אינטרוברסיה, התנגדות לניחומים כשעצוב, כאבי ראש מחמירים בשמש, משתפרים מלחץ, ריריות יבשות המתחלפות עם הפרשות מימיות, כיבים קרים סביב השפתיים, עצירות עם צואה מתפוררת, הצטננויות עם הפרשת אף כמו חלבון ביצה, תשוקות למזונות מלוחים מחמיר משמש, חום, 10-11 בבוקר, ניחומים; משתפר מאוויר פתוח קריר, שכיבה על צד ימין', 169.90, 'product.png'),
(UUID(), 'Phytolacca Decandra', 'Phytolacca Decandra', 'Pokeweed plant Glandular system, throat, musculoskeletal, Glandular swelling and inflammation, Mastitis with hard, hot, painful breasts, Sore throats with dark red/purple tonsils, Electric shock-like joint pains, Muscular stiffness and soreness, Indifference and apathy from pain, Ulcers and skin lesions, Teething with irresistible biting Modalities: Worse from cold, damp, night, motion, swallowing; Better from warmth, rest, rubbing affected parts', 'תיאור בעברית לא זמין; יש לתרגם', 169.90, 'product.png'),
(UUID(), 'Psorinum', 'Psorinum', 'Scabies nosode Chronic conditions, skin, offensive discharges, Despair of recovery and hopelessness, Extreme anxiety and impending doom, Offensive odors from all bodily secretions, Intense itching worse from warmth, Chronic eczema and psoriasis, Respiratory asthma with suffocation, Weakness, anemia, and lack of vitality, Ravenous appetite especially at night Modalities: Worse from cold, drafts, warmth of bed, before storms; Better from warmth, being bundled up Herbal/Natural Medicine Products', 'תיאור בעברית לא זמין; יש לתרגם', 169.90, 'product.png'),
(UUID(), 'Berberis Vulgaris (Barberry)', 'Berberis Vulgaris (Barberry)', 'Barberry plant Diabetes management, Contains protoberberine alkaloids (berberine), Antihyperglycemic effects, Modest reductions in fasting plasma glucose, HbA1c improvements, HOMA-IR reductions, Small effects on post-prandial glucose, Gastrointestinal adverse effects possible, Contraindicated in pregnancy/lactation Clinical Evidence: RCTs show significant but modest glycemic control benefits', 'תיאור בעברית לא זמין; יש לתרגם', 169.90, 'product.png'),
(UUID(), 'Gymnema Sylvestre', 'Gymnema Sylvestre', 'Gymnema plant Blood sugar regulation and diabetes, Reduces sugar cravings by blocking taste receptors, Lowers blood sugar levels and post-meal spikes, Supports insulin production and beta-cell regeneration, Improves cholesterol and triglyceride levels, Aids weight management and appetite suppression, Anti-inflammatory and immunomodulatory effects, Traditional Ayurvedic diabetes treatment Clinical Evidence: Meta-analyses show significant reductions in FPG, HbA1c, and lipids', 'תיאור בעברית לא זמין; יש לתרגם', 169.90, 'product.png'),
(UUID(), 'Momordica Charantia (Bitter Melon)', 'Momordica Charantia (Bitter Melon)', 'Bitter melon plant Diabetes management, Blood sugar regulation, Insulin sensitivity improvement, Pancreatic function support, Anti-diabetic properties, Traditional diabetes treatment, Metabolic health support Clinical Evidence: Limited direct evidence for homeopathic use, but herbal form shows glycemic benefits', 'תיאור בעברית לא זמין; יש לתרגם', 169.90, 'product.png'),
(UUID(), 'Silybum Marianum (Milk Thistle)', 'סיליבום מריאנום (חלב קוץ)', 'Milk thistle seeds Liver and gallbladder health, Liver congestion, swelling, and tenderness, Gallstones and biliary colic, Jaundice from liver dysfunction, Hepatitis and early cirrhosis, Indigestion after rich/fatty foods, Nausea and bitter taste, Pale stools and constipation, Portal vein congestion effects Modalities: Worse from lying on right side, cold, rich foods; Better from warmth, light exercise, hot water bottle', ' זרעי חלב קוץ  בריאות כבד וכיס מרה, עומס בכבד, נפיחות ורגישות, אבני מרה וקוליקה ביליארית, צהבת מתפקוד לקוי של הכבד, הפטיטיס וצירוזיס מוקדם, עיכול לקוי לאחר מזונות עשירים/שומניים, בחילה וטעם מר, צואה חיוורת ועצירות, השפעות עומס וריד שער מחמיר משכיבה על צד ימין, קור, מזונות עשירים; משתפר מחום, פעילות גופנית קלה, בקבוק מים חמים', 169.90, 'product.png'),
(UUID(), 'Punica Granatum L. (Pomegranate)', 'פוניקה גרנטום ל. (רימון)', 'Pomegranate tree Parasitic infections, digestive system, Tapeworm and intestinal parasite expulsion, Chronic diarrhea from parasitic infection, Ravenous hunger not satisfied by eating, Nausea and vomiting with empty stomach feeling, Abdominal pain around navel, Mental emptiness and weakness, Headaches and vertigo, Emaciation despite huge appetite Modalities: Worse from cold, eating, mental exertion; Better from warmth, rest', ' עץ רימון  זיהומים טפיליים, מערכת עיכול, גירוש תולעי סרט ומעיים, שלשול כרוני מזיהום טפילי, רעב עז שאינו מסופק מאכילה, בחילה והקאות עם תחושת קיבה ריקה, כאב בטן סביב הטבור, ריקנות מנטלית וחולשה, כאבי ראש וסחרחורת, רזון למרות תיאבון עצום מחמיר מקור, אכילה, מאמץ מנטלי; משתפר מחום, מנוחה', 169.90, 'product.png'),
(UUID(), 'Uranium Nitricum', 'אורניום ניטריקום', 'Uranium nitrate Metabolic disorders, diabetes, urinary system, Diabetes mellitus with high blood sugar, Emaciation with enormous appetite, Frequent and profuse urination (nocturia), Painful urination and bladder discomfort, Liver and kidney dysfunction, Digestive upset and abdominal bloating, General weakness and fatigue, High blood pressure from metabolic issues Modalities: Worse from cold, eating, mental exertion; Better from warmth, rest', ' אורניום ניטרט  הפרעות מטבוליות, סוכרת, מערכת שתן, סוכרת מליטוס עם סוכר גבוה בדם, רזון עם תיאבון עצום, השתנה תכופה ומרובה (נוקטוריה), השתנה כואבת ואי נוחות בשלפוחית, תפקוד לקוי של כבד וכליות, הפרעה עיכול ונפיחות בטנית, חולשה כללית ועייפות, לחץ דם גבוה מבעיות מטבוליות מחמיר מקור, אכילה, מאמץ מנטלי; משתפר מחום, מנוחה', 169.90, 'product.png'),
(UUID(), 'Vanadium', 'ונדיום', 'Trace mineral Blood sugar regulation, diabetes, Insulin-mimetic properties, Improved glucose homeostasis, Enhanced insulin sensitivity, Reduced hepatic gluconeogenesis, Improved lipid profiles, Blood sugar regulation, Metabolic health support Clinical Evidence: Preclinical studies show glucose-lowering effects, limited human trials Database Statistics, Total Products: 35+ documented products, Homeopathic Remedies: ~25 classical remedies, Herbal Products: ~10 plant-based medicines, Specialized Focus: Diabetes management (multiple products), Documentation Quality: Detailed therapeutic profiles with clinical evidence This comprehensive database provides a solid foundation for a professional natural medicine e-commerce platform.', ' מינרל מעקב  ויסות סוכר בדם, סוכרת, תכונות דמויי אינסולין, הומאוסטזיס גלוקוז משופרת, רגישות לאינסולין מוגברת, גלוקונאוגנזה כבדית מופחתת, פרופילי שומנים משופרים, ויסות סוכר בדם, תמיכה בבריאות מטבולית ראיות קליניות: מחקרים פרה-קליניים מראים השפעות מורידות גלוקוז, ניסויים אנושיים מוגבלים סטטיסטיקות מסד נתונים, סך מוצרים: 35+ מוצרים מתועדים, תרופות הומאופתיות: ~25 תרופות קלאסיות, מוצרים צמחיים: ~10 מוצרים צמחיים, מיקוד מיוחד: ניהול סוכרת (מוצרים מרובים), איכות תיעוד: פרופילים טיפוליים מפורטים עם ראיות קליניות מסד נתונים מקיף זה מספק בסיס מוצק לפלטפורמת מסחר אלקטרוני מקצועית לרפואה טבעית.', 169.90, 'product.png');
